### ISSUE TITLE
Reconnect issue in Websocket

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#22]
```
Aug 06 10:45:08 igel metricq-sink-websocket[31406]: Traceback (most recent call last):
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/metricq-sink-websocket/metricq_sink_websocket/views.py", line 28, in websocket_handler
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     metadata = await sink.subscribe_ws(ws, new_metrics - metrics)
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/metricq-sink-websocket/metricq_sink_websocket/sink.py", line 130, in subscribe_ws
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     response = await self.subscribe(list(subscribe_metrics), metadata=True)
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/metricq-sink-websocket/metricq_sink_websocket/sink.py", line 103, in subscribe
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     return await super().subscribe(self._primary_to_internal(metrics), **kwargs)
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/envs/websocket/lib/python3.7/site-packages/metricq/sink.py", line 134, in subscribe
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     response = await self.rpc("sink.subscribe", metrics=metrics, **kwargs)
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/envs/websocket/lib/python3.7/site-packages/metricq/client.py", line 75, in rpc
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     await self._management_connection_watchdog.established()
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:   File "/home/service/envs/websocket/lib/python3.7/site-packages/metricq/connection_watchdog.py", line 114, in established
Aug 06 10:45:08 igel metricq-sink-websocket[31406]:     await self._established_event.wait()
Aug 06 10:45:08 igel metricq-sink-websocket[31406]: AttributeError: 'NoneType' object has no attribute 'wait'
```

**Comment by bmario** [comment]
This will be fixed with once https://github.com/mosquito/aio-pika/pull/344 is availabe in a release :(
