### ISSUE TITLE
stop() failure

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-python#48]
With a `HistoryClient`

```
await client.stop()

Callback error
Traceback (most recent call last):
  File "lib/python3.8/site-packages/aio_pika/tools.py", line 166, in __call__
    cb(self.__sender(), *args, **kwargs)
TypeError: _on_close() takes 2 positional arguments but 3 were given
Callback error
Traceback (most recent call last):
  File "lib/python3.8/site-packages/aio_pika/tools.py", line 166, in __call__
    cb(self.__sender(), *args, **kwargs)
TypeError: _on_close() takes 2 positional arguments but 3 were given
Callback error
Traceback (most recent call last):
  File "lib/python3.8/site-packages/aio_pika/tools.py", line 166, in __call__
    cb(self.__sender(), *args, **kwargs)
TypeError: _on_management_connection_close() takes 2 positional arguments but 3 were given
```

Did `aio_pika` break us again?

**Comment by bmario** [comment]
Yes, #44 also fixes that.
