### ISSUE TITLE
history client reconnect issues

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-python#75]
```
-- Logs begin at Sat 2021-02-27 23:06:26 CET, end at Tue 2021-03-02 14:13:01 CET. --
Mar 02 13:42:03 igel metricq.agent[103468]: Connection closed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'") (ConnectionClosed)
Mar 02 13:42:03 igel aio_pika.robust_connection[103468]: Connection to amqps://http:******@rabbitmq.metricq.zih.tu-dresden.de:5671/data closed. Reconnecting after 5 seconds.
Mar 02 13:42:03 igel aiohttp.server[103468]: Error handling request
                                             Traceback (most recent call last):
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/base.py", line 25, in __inner
                                                 return await self.task
                                             concurrent.futures._base.CancelledError
                                             
                                             The above exception was the direct cause of the following exception:
                                             
                                             Traceback (most recent call last):
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
                                                 resp = await task
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
                                                 resp = await handler(request)
                                               File "/home/service/metricq-grafana/metricq_grafana/views.py", line 74, in legacy_counter_data
                                                 int(data["width"]),
                                               File "/home/service/metricq-grafana/metricq_grafana/amqp.py", line 127, in get_counter_data
                                                 target.get_metadata(app),
                                               File "/home/service/metricq-grafana/metricq_grafana/target.py", line 48, in get_response
                                                 self._get_data(app, start_time, end_time, interval), self._get_metadata(app)
                                               File "/home/service/envs/grafana/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
                                                 return (yield from awaitable.__await__())
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/base.py", line 27, in __inner
                                                 raise self.exception from e
                                               File "/home/service/metricq-grafana/metricq_grafana/target.py", line 81, in _get_data
                                                 request_type=HistoryRequestType.FLEX_TIMELINE,
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/metricq/history_client.py", line 413, in history_data_request
                                                 await self.history_exchange.publish(msg, metric)
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aio_pika/exchange.py", line 242, in publish
                                                 timeout=timeout,
                                               File "/home/service/envs/grafana/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
                                                 return await fut
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/channel.py", line 547, in basic_publish
                                                 return await asyncio.wait_for(confirmation, timeout=timeout)
                                               File "/home/service/envs/grafana/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
                                                 return await fut
                                             aiormq.exceptions.ConnectionClosed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
Mar 02 13:42:03 igel metricq.agent[103468]: Connection closed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'") (ConnectionClosed)
Mar 02 13:42:03 igel aio_pika.robust_connection[103468]: Connection to amqps://http:******@rabbitmq.metricq.zih.tu-dresden.de:5671/ closed. Reconnecting after 5 seconds.
Mar 02 13:42:03 igel aiohttp.server[103468]: Error handling request
                                             Traceback (most recent call last):
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
                                                 resp = await task
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
                                                 resp = await handler(request)
                                               File "/home/service/metricq-grafana/metricq_grafana/views.py", line 74, in legacy_counter_data
                                                 int(data["width"]),
                                               File "/home/service/metricq-grafana/metricq_grafana/amqp.py", line 127, in get_counter_data
                                                 target.get_metadata(app),
                                               File "/home/service/metricq-grafana/metricq_grafana/target.py", line 48, in get_response
                                                 self._get_data(app, start_time, end_time, interval), self._get_metadata(app)
                                               File "/home/service/metricq-grafana/metricq_grafana/target.py", line 81, in _get_data
                                                 request_type=HistoryRequestType.FLEX_TIMELINE,
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/metricq/history_client.py", line 413, in history_data_request
                                                 await self.history_exchange.publish(msg, metric)
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aio_pika/exchange.py", line 242, in publish
                                                 timeout=timeout,
                                               File "/home/service/envs/grafana/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
                                                 return await fut
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/channel.py", line 508, in basic_publish
                                                 async with self.lock:
                                               File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/channel.py", line 90, in lock
                                                 raise ChannelInvalidStateError("%r closed" % self)
                                             aiormq.exceptions.ChannelInvalidStateError: <Channel: "1"> closed
:
```

**Comment by tilsche** [comment]
Happened again after the netsplit yesterday.

```
2021-06-24T19:03:31.055941+02:00 metricq metricq-grafana[54546]: 2021-06-24 19:03:30,880 [WARNING ] [aio_pika.robust_connection] Connection attempt to "amqps://http:******@rabbitmq.metricq.zih.tu-dresden.de:5671/" failed. Reconnecting after 5 seconds.
2021-06-24T19:03:31.056327+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:31.056423+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/connection.py", line 375, in __reader
2021-06-24T19:03:31.056522+02:00 metricq metricq-grafana[54546]:     weight, channel, frame = await self.__receive_frame()
2021-06-24T19:03:31.056605+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/connection.py", line 327, in __receive_frame
2021-06-24T19:03:31.056712+02:00 metricq metricq-grafana[54546]:     frame_header = await self.reader.readexactly(1)
2021-06-24T19:03:31.056798+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/streams.py", line 723, in readexactly
2021-06-24T19:03:31.056881+02:00 metricq metricq-grafana[54546]:     await self._wait_for_data('readexactly')
2021-06-24T19:03:31.056982+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
2021-06-24T19:03:31.057066+02:00 metricq metricq-grafana[54546]:     await self._waiter
2021-06-24T19:03:31.057146+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
2021-06-24T19:03:31.057224+02:00 metricq metricq-grafana[54546]:     ssldata, appdata = self._sslpipe.feed_ssldata(data)
2021-06-24T19:03:31.057320+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 206, in feed_ssldata
2021-06-24T19:03:31.057417+02:00 metricq metricq-grafana[54546]:     self._sslobj.unwrap()
2021-06-24T19:03:31.057514+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/ssl.py", line 948, in unwrap
2021-06-24T19:03:31.057595+02:00 metricq metricq-grafana[54546]:     return self._sslobj.shutdown()
2021-06-24T19:03:31.057700+02:00 metricq metricq-grafana[54546]: ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2745)
2021-06-24T19:03:31.057814+02:00 metricq metricq-grafana[54546]: During handling of the above exception, another exception occurred:
2021-06-24T19:03:31.057904+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:31.057985+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/connection.py", line 413, in __reader
2021-06-24T19:03:31.058050+02:00 metricq metricq-grafana[54546]:     await self.close(e)
2021-06-24T19:03:31.058130+02:00 metricq metricq-grafana[54546]: asyncio.exceptions.CancelledError
2021-06-24T19:03:31.058209+02:00 metricq metricq-grafana[54546]: During handling of the above exception, another exception occurred:
2021-06-24T19:03:31.058286+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:31.058383+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 25, in __inner
2021-06-24T19:03:31.058488+02:00 metricq metricq-grafana[54546]:     return await self.task
2021-06-24T19:03:31.058571+02:00 metricq metricq-grafana[54546]: asyncio.exceptions.CancelledError
2021-06-24T19:03:31.058651+02:00 metricq metricq-grafana[54546]: The above exception was the direct cause of the following exception:
2021-06-24T19:03:31.058729+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:31.058807+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/robust_connection.py", line 132, in connect
2021-06-24T19:03:31.058884+02:00 metricq metricq-grafana[54546]:     await channel.reopen()
2021-06-24T19:03:31.059013+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/robust_channel.py", line 58, in reopen
2021-06-24T19:03:31.059119+02:00 metricq metricq-grafana[54546]:     await self.restore()
2021-06-24T19:03:31.059224+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/robust_channel.py", line 75, in restore
2021-06-24T19:03:31.059326+02:00 metricq metricq-grafana[54546]:     await queue.restore(self)
2021-06-24T19:03:31.059405+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/robust_queue.py", line 59, in restore
2021-06-24T19:03:31.059498+02:00 metricq metricq-grafana[54546]:     await self.declare()
2021-06-24T19:03:31.059580+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/queue.py", line 92, in declare
2021-06-24T19:03:31.059657+02:00 metricq metricq-grafana[54546]:     self.declaration_result = await asyncio.wait_for(
2021-06-24T19:03:31.059734+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
2021-06-24T19:03:31.059842+02:00 metricq metricq-grafana[54546]:     return await fut
2021-06-24T19:03:31.059935+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/channel.py", line 703, in queue_declare
2021-06-24T19:03:31.060013+02:00 metricq metricq-grafana[54546]:     return await self.rpc(
2021-06-24T19:03:31.060103+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 168, in wrap
2021-06-24T19:03:31.060197+02:00 metricq metricq-grafana[54546]:     return await self.create_task(func(self, *args, **kwargs))
2021-06-24T19:03:31.060280+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 27, in __inner
2021-06-24T19:03:31.060392+02:00 metricq metricq-grafana[54546]:     raise self.exception from e
2021-06-24T19:03:31.060478+02:00 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 687, in _wrap_awaitable
2021-06-24T19:03:31.060561+02:00 metricq metricq-grafana[54546]:     return (yield from awaitable.__await__())
2021-06-24T19:03:31.060656+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 27, in __inner
2021-06-24T19:03:31.060736+02:00 metricq metricq-grafana[54546]:     raise self.exception from e
2021-06-24T19:03:31.060816+02:00 metricq metricq-grafana[54546]: aiormq.exceptions.ChannelLockedResource: RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'history-grafana-debug-rpc' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.
2021-06-24T19:03:35.852026+02:00 metricq metricq-sink-websocket[126898]: 2021-06-24 19:03:35,850 [INFO    ] [metricq.agent       ] starting RPC consume
2021-06-24T19:03:45.184156+02:00 metricq metricq-grafana[54546]: 2021-06-24 19:03:45,052 [ERROR   ] [aiohttp.server      ] Error handling request
2021-06-24T19:03:45.184390+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:45.184486+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 143, in __closer
2021-06-24T19:03:45.184568+02:00 metricq metricq-grafana[54546]:     await self._cancel_tasks(exc)
2021-06-24T19:03:45.184646+02:00 metricq metricq-grafana[54546]: asyncio.exceptions.CancelledError
2021-06-24T19:03:45.184724+02:00 metricq metricq-grafana[54546]: During handling of the above exception, another exception occurred:
2021-06-24T19:03:45.184829+02:00 metricq metricq-grafana[54546]: Traceback (most recent call last):
2021-06-24T19:03:45.185046+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/connection.py", line 316, in __heartbeat_task
2021-06-24T19:03:45.185161+02:00 metricq metricq-grafana[54546]:     await self.close(
2021-06-24T19:03:45.185281+02:00 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/base.py", line 149, in close
```

```
Jun 25 09:37:18 metricq metricq-grafana[54546]: 2021-06-25 09:37:18,589 [ERROR   ] [aiohttp.server      ] Error handling request
Jun 25 09:37:18 metricq metricq-grafana[54546]: Traceback (most recent call last):
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Jun 25 09:37:18 metricq metricq-grafana[54546]:     resp = await self._request_handler(request)
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
Jun 25 09:37:18 metricq metricq-grafana[54546]:     resp = await handler(request)
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/views.py", line 25, in query
Jun 25 09:37:18 metricq metricq-grafana[54546]:     resp = await get_history_data(request.app, req_json)
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/amqp.py", line 44, in get_history_data
Jun 25 09:37:18 metricq metricq-grafana[54546]:     results = await asyncio.gather(
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 47, in get_response
Jun 25 09:37:18 metricq metricq-grafana[54546]:     ((data, time_delta_ns), metadata) = await asyncio.gather(
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 75, in _get_data
Jun 25 09:37:18 metricq metricq-grafana[54546]:     data = await app["history_client"].history_data_request(
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq/history_client.py", line 433, in history_data_request
Jun 25 09:37:18 metricq metricq-grafana[54546]:     await self.history_exchange.publish(msg, routing_key=metric)
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aio_pika/exchange.py", line 233, in publish
Jun 25 09:37:18 metricq metricq-grafana[54546]:     return await asyncio.wait_for(
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
Jun 25 09:37:18 metricq metricq-grafana[54546]:     return await fut
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/channel.py", line 508, in basic_publish
Jun 25 09:37:18 metricq metricq-grafana[54546]:     async with self.lock:
Jun 25 09:37:18 metricq metricq-grafana[54546]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiormq/channel.py", line 90, in lock
Jun 25 09:37:18 metricq metricq-grafana[54546]:     raise ChannelInvalidStateError("%r closed" % self)
Jun 25 09:37:18 metricq metricq-grafana[54546]: aiormq.exceptions.ChannelInvalidStateError: <Channel: "1"> closed
Jun 25 09:37:18 metricq metricq-grafana[54546]: 2021-06-25 09:37:18,626 [ERROR   ] [aiohttp.server      ] Error handling request
```
