### ISSUE TITLE
Setting period to None in IntervalSource

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-python#92]
When setting `self.period = None` in a class derived from `IntervalSource`, you get a quite unintuitive error:

```
Mar 29 18:23:35 energy metricq-source-watchport[979]: initializing WatchPortSource
Mar 29 18:23:35 energy metricq-source-watchport[979]: Initialized Agent `WatchPortSource` (running version `metricq==2.0.0`)
Mar 29 18:23:35 energy metricq-source-watchport[979]: warning: Failed to find version of WatchPortSource: module 'metricq_source_watchport.source' has no attribute '__version__'
Mar 29 18:23:35 energy metricq-source-watchport[979]: Initializing client (version: unknown)
Mar 29 18:23:35 energy metricq-source-watchport[979]: Traceback (most recent call last):
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/bin/metricq-source-watchport", line 8, in <module>
Mar 29 18:23:35 energy metricq-source-watchport[979]:     sys.exit(source())
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
Mar 29 18:23:35 energy metricq-source-watchport[979]:     return self.main(*args, **kwargs)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
Mar 29 18:23:35 energy metricq-source-watchport[979]:     rv = self.invoke(ctx)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
Mar 29 18:23:35 energy metricq-source-watchport[979]:     return ctx.invoke(self.callback, **ctx.params)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
Mar 29 18:23:35 energy metricq-source-watchport[979]:     return callback(*args, **kwargs)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/metricq_source_watchport/main.py", line 22, in source
Mar 29 18:23:35 energy metricq-source-watchport[979]:     src = WatchPortSource(token=token, management_url=server)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/metricq_source_watchport/source.py", line 14, in __init__
Mar 29 18:23:35 energy metricq-source-watchport[979]:     self.period = None
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/metricq/interval_source.py", line 104, in period
Mar 29 18:23:35 energy metricq-source-watchport[979]:     self._period = Timedelta.from_s(duration)
Mar 29 18:23:35 energy metricq-source-watchport[979]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.8/site-packages/metricq/types.py", line 207, in from_s
Mar 29 18:23:35 energy metricq-source-watchport[979]:     return Timedelta(int(seconds * 1e9))
Mar 29 18:23:35 energy metricq-source-watchport[979]: TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

Instead, the property should raise `ValueError`.

**Comment by phijor** [comment]
I'd say we reraise the `TypeError` with a more descriptive message.  A `ValueError` would indicate an argument of the correct type, which `None` has not.

Also:

https://github.com/metricq/metricq-python/blob/ebe4382665c59df36f3e4701b384d19f1c063304/tests/test_interval_source.py#L45-L50

Maybe we should add this comment to the documentation.

**Comment by bmario** [comment]
I've seen code like this:

```
class MySource(IntervalSource):
    def __init__(self):
        self.period = None
```

In that case, the new message is overspecified. `period` cannot be set to `None`, regardless of the prior state. The error should reflect that.

**Comment by phijor** [comment]
Oh, I did not know there's sources that do that. Will get on it.
